---
title: "fabl_with_duplicates"
output: html_document
date: "2024-03-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Functions

```{r}
devtools::load_all()
```

## Variational FastLink vs vabl

The discrepancy between fastlink and fabl seems to be more pronounced when there are more matches. This makes sense, because more shrinkage is occuring. 
```{r}
n1 <- 1000 # target
n2 <- 1000 # base
overlap <- n1 * .9 #for more shrinkage

m <- rep(c(.95, .05), 5)
u <- c(.01, .99, .01, .99,
       1/30, 1- 1/30, 1/12, 1 - 1/12, 1/15, 1 - 1/15)

levels <- rep(2, 5)
cd <- simulate_comparisons(m, u, levels, n1, n2, overlap)
hash <- hash_comparisons(cd, all_patterns = F)

out_fl <- variational_fastlink(hash)
estimate_fl <- estimate_links_fl(out_fl, hash)
eval_fs_normalization <- evaluate_links(estimate_fl$Z_hat, cd$Z_true, n1)
eval_fs_jaro <- evaluate_links(estimate_fl$Z_hat_jaro, cd$Z_true, n1)

out_vabl <- vabl(hash)
estimate_vabl <- estimate_links(out_vabl, hash)
eval_vabl <- evaluate_links(estimate_vabl$Z_hat, cd$Z_true, n1)

KL_fs <- estimate_fl$params_patterns$KL
KL_vabl <- estimate_vabl$params_patterns$KL

list(fs_jaro = eval_fs_jaro, 
     fs_normalization = eval_fs_normalization, 
     vabl = eval_fs_jaro, 
     KL_fs = KL_fs, 
     KL_vabl = KL_vabl)
```


