---
title: "fabl_with_duplicates"
output: html_document
date: "2024-03-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Functions

```{r}
devtools::load_all()
```

## Variational FastLink vs vabl


```{r}
n1 <- 1000 # target
n2 <- 1000 # base
overlap <- n1 * .1 

m <- rep(c(.95, .05), 5)
u <- c(.01, .99, .01, .99,
       1/30, 1- 1/30, 1/12, 1 - 1/12, 1/15, 1 - 1/15)

levels <- rep(2, 5)
cd <- simulate_comparisons(m, u, levels, n1, n2, overlap)
hash <- hash_comparisons(cd, all_patterns = F)

out_fl <- variational_fastlink(hash)
estimate_fl <- estimate_links_fl(out_fl, hash)
eval_fs_normalization <- evaluate_links(estimate_fl$Z_hat, cd$Z_true, n1)
eval_fs_jaro <- evaluate_links(estimate_fl$Z_hat_jaro, cd$Z_true, n1)

out_vabl <- vabl(hash)
estimate_vabl <- estimate_links(out_vabl, hash)
eval_vabl <- evaluate_links(estimate_vabl$Z_hat, cd$Z_true, n1)

list(fs_jaro = eval_fs_jaro, 
     fs_normalization = eval_fs_normalization, 
     vabl = eval_fs_vabl)
```


```{r}
x <- matrix(1:12,3,4)
y <- x+100
dim(abind(x,y,along=0))     # binds on new dimension before first
dim(abind(x,y,along=1))     # binds on first dimension
dim(abind(x,y,along=1.5))
dim(abind(x,y,along=2))
dim(abind(x,y,along=3))
dim(abind(x,y,rev.along=1)) # binds on last dimension
dim(abind(x,y,rev.along=0)) # binds on new dimension after last

# Unlike cbind or rbind in that the default is to bind
# along the last dimension of the inputs, which for vectors
# means the result is a vector (because a vector is
# treated as an array with length(dim(x))==1).
abind(x=1:4,y=5:8)
# Like cbind
abind(x=1:4,y=5:8,along=2)
abind(x=1:4,matrix(5:20,nrow=4),along=2)
abind(1:4,matrix(5:20,nrow=4),along=2)
# Like rbind
abind(x=1:4,matrix(5:20,nrow=4),along=1)
abind(1:4,matrix(5:20,nrow=4),along=1)
# Create a 3-d array out of two matrices
abind(x=matrix(1:16,nrow=4),y=matrix(17:32,nrow=4),along=3)
# Use of hier.names
abind(x=cbind(a=1:3,b=4:6), y=cbind(a=7:9,b=10:12), hier.names=TRUE)
# Use a list argument
abind(list(x=x, y=x), along=3)
# Use lapply(..., get) to get the objects
an <- c('x','y')
names(an) <- an
abind(lapply(an, get), along=3)
```
```{r}
abind(thing, rep(NA, 2), along = 1)
abind(thing, array(0, dim = replace(dim(thing), 2, 1)), along = 2)
```

